services:
  server-ci:
    build:
      context: ./server
      dockerfile: Dockerfile.production
    ports:
      - 3001:3001
    networks:
      - ci
    container_name: holenav-server-ci
    environment:
      - NODE_ENV=test
      - PORT=3001
      - MONGO_URL=mongodb://mongo-ci/ci
      - NEO_URL=neo4j://neo-ci
      - NEO_DB=neo4j
      - CLIENT_URL=http://client-ci:3000
      - JWT_SECRET=asdasd
      - ENABLE_DEVTOOLS=true
    depends_on:
      - mongo-ci
      - neo-ci

  client-ci:
    build: ./client/
    ports:
      - 3000:3000
      - 30011:30011
    networks:
      - ci
    container_name: holenav-client-ci
    environment:
      - PORT=3000
      - INTERNAL_STATUS_PORT=30011
      - REACT_APP_BACKEND_URL=http://server-ci:3001
      - REACT_APP_ENABLE_DEVTOOLS=true

  mongo-ci:
    image: mongo:4.4-bionic
    restart: unless-stopped
    container_name: holenav-mongo-ci
    ports:
      - 27017:27017
    networks:
      - ci

  neo-ci:
    image: neo4j:4.4
    restart: unless-stopped
    container_name: holenav-neo-ci
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - ci

  e2e-ci:
    build: ./e2e/
    networks:
      - ci
    container_name: holenav-e2e-ci
    environment:
      - CYPRESS_BASE_URL=http://client-ci:3000
      - CYPRESS_API_URL=http://server-ci:3001
    volumes:
      - ./e2e/cypress:/e2e/cypress
    depends_on:
      - server-ci

networks:
  ci:
