services:
  server:
    build: .
    container_name: holenav-server-ci
    networks:
      - ci
    environment:
      - NODE_ENV=test
      - PORT=3001
      - MONGO_URL=mongodb://mongo/ci
      - NEO_URL=neo4j://neo
      - NEO_DB=neo4j
      - CLIENT_URL=http://web:5173
      - JWT_SECRET=asdasd
      - ENABLE_DEVTOOLS=true
      - SSO_CLIENT_ID=asd
      - SSO_SECRET_KEY=asd
      - SSO_CALLBACK_URL=asd
      - SESSION_SECRET=dsqefw
    depends_on:
      - mongo
      - neo

  web:
    extends:
      file: compose.common.yaml
      service: web-base
    container_name: holenav-web-ci
    networks:
      - ci
    environment:
      - VITE_BACKEND_URL=http://server:3001

  mongo:
    extends:
      file: compose.common.yaml
      service: mongo-base
    container_name: holenav-mongo-ci
    networks:
      - ci

  neo:
    extends:
      file: compose.common.yaml
      service: neo-test-base
    container_name: holenav-neo-ci
    networks:
      - ci

  e2e:
    build: ./e2e/
    networks:
      - ci
    container_name: holenav-e2e
    environment:
      - CYPRESS_BASE_URL=http://web:5173
      - CYPRESS_API_URL=http://server:3001
    volumes:
      - ./e2e/cypress:/e2e/cypress
    depends_on:
      - server

networks:
  ci:
