services:
  server:
    build: .
    container_name: holenav-server-ci
    networks:
      - ci
    environment:
      - NODE_ENV=test
      - PORT=3001
      - MONGO_URL=mongodb://mongo/ci
      - CLIENT_URL=http://web:5173
      - JWT_SECRET=asdasd
      - ENABLE_DEVTOOLS=true
      - SSO_CLIENT_ID=asd
      - SSO_SECRET_KEY=asd
      - SSO_CALLBACK_URL=asd
      - SESSION_SECRET=dsqefw
    depends_on:
      - mongo

  web:
    extends:
      file: compose.common.yaml
      service: web-base
    container_name: holenav-web-ci
    networks:
      - ci
    environment:
      - VITE_BACKEND_URL=http://server:3001

  mongo:
    extends:
      file: compose.common.yaml
      service: mongo-base
    container_name: holenav-mongo-ci
    networks:
      - ci

networks:
  ci:
