services:
  web:
    extends:
      file: compose.common.yaml
      service: web-base
    container_name: holenav-web
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    ports:
      - 3000:5173

  web-test:
    extends:
      file: compose.common.yaml
      service: web-base
    container_name: holenav-web-test
    environment:
      - VITE_BACKEND_URL=http://localhost:4001
    ports:
      - 4000:5173

  server:
    extends:
      file: compose.common.yaml
      service: server-base
    container_name: holenav-server
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo/holenav
      - CLIENT_URL=http://localhost:3000
      - SSO_CALLBACK_URL=http://localhost:3001/sso/callback
    env_file:
      - .env.development
    depends_on:
      - mongo

  server-test:
    extends:
      file: compose.common.yaml
      service: server-base
    container_name: holenav-server-test
    ports:
      - 4001:4001
    environment:
      - PORT=4001
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo/holenav-test
      - CLIENT_URL=http://localhost:4000
      - SSO_CLIENT_ID=asd
      - SSO_SECRET_KEY=asd
      - SSO_CALLBACK_URL=http://localhost:4001/sso/callback
      - AUTHORIZATION_URL=http://localhost:4001/sso/callback?code=asd
    depends_on:
      - mongo

  mongo:
    extends:
      file: compose.common.yaml
      service: mongo-base
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
        volume:
          nocopy: true

volumes:
  mongo-data:
