services:
  web-base:
    build: ./web/
    environment:
      - VITE_ENABLE_DEVTOOLS=true
    volumes:
      - ./web/src:/usr/src/app/src

  web:
    extends: web-base
    container_name: holenav-web
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    ports:
      - 3000:5173

  web-test:
    extends: web-base
    container_name: holenav-web-test
    environment:
      - VITE_BACKEND_URL=http://localhost:4001
    ports:
      - 4000:5173

  server-base:
    build: ./server/
    environment:
      - PORT=3001
      - NEO_DB=neo4j
      - JWT_SECRET=asdasd
      - ENABLE_DEVTOOLS=true
    volumes:
      - ./server/src:/usr/src/app/src

  server:
    extends: server-base
    container_name: holenav-server
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo/holenav
      - NEO_URL=neo4j://neo
      - CLIENT_URL=http://localhost:3000
    env_file:
      - .env.development
    depends_on:
      - mongo
      - neo

  server-test:
    extends: server-base
    container_name: holenav-server-test
    ports:
      - 4001:3001
    environment:
      - NODE_ENV=test
      - MONGO_URL=mongodb://mongo/holenav-test
      - NEO_URL=neo4j://neo-test
      - CLIENT_URL=http://localhost:4000
    depends_on:
      - mongo
      - neo-test

  mongo:
    image: mongo:5.0-focal
    restart: unless-stopped
    container_name: holenav-mongo
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
        volume:
          nocopy: true
    ports:
      - 27017:27017

  neo:
    image: neo4j:4.4
    restart: unless-stopped
    container_name: holenav-neo
    environment:
      - NEO4J_AUTH=none
    volumes:
      - type: volume
        source: neo-data
        target: /data
    ports:
      - 7474:7474
      - 7687:7687

  # Community edition does not allow multiple databases, so we must spin up another container for tests.
  neo-test:
    image: neo4j:4.4
    restart: unless-stopped
    container_name: holenav-neo-test
    environment:
      - NEO4J_AUTH=none
    ports:
      - 7475:7474
      - 7688:7687

volumes:
  mongo-data:
  neo-data:
