services:
  web-base:
    build: ./web/
    environment:
      - VITE_ENABLE_DEVTOOLS=true
    volumes:
      - ./web/src:/usr/src/app/src

  server-base:
    build:
      context: server
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3001
      - ENABLE_DEVTOOLS=true
      - SESSION_SECRET=dsqefw
    volumes:
      - ./server/src:/usr/src/app/src

  mongo-base:
    image: mongo:5.0-focal
    restart: unless-stopped
    container_name: holenav-mongo
    ports:
      - 27017:27017
