services:
  web:
    extends:
      file: compose.common.yaml
      service: web-base
    container_name: holenav-web
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    ports:
      - 3000:5173

  web-test:
    extends:
      file: compose.common.yaml
      service: web-base
    container_name: holenav-web-test
    environment:
      - VITE_BACKEND_URL=http://localhost:4001
    ports:
      - 4000:5173

  server:
    extends:
      file: compose.common.yaml
      service: server-base
    container_name: holenav-server
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo/holenav
      - NEO_URL=neo4j://neo
      - CLIENT_URL=http://localhost:3000
    env_file:
      - .env.development
    depends_on:
      - mongo
      - neo

  server-test:
    extends:
      file: compose.common.yaml
      service: server-base
    container_name: holenav-server-test
    ports:
      - 4001:3001
    environment:
      - NODE_ENV=test
      - MONGO_URL=mongodb://mongo/holenav-test
      - NEO_URL=neo4j://neo-test
      - CLIENT_URL=http://localhost:4000
    depends_on:
      - mongo
      - neo-test

  mongo:
    extends:
      file: compose.common.yaml
      service: mongo-base

  neo:
    extends:
      file: compose.common.yaml
      service: neo-base

  # Community edition does not allow multiple databases, so we must spin up another container for tests.
  neo-test:
    extends:
      file: compose.common.yaml
      service: neo-test-base

volumes:
  mongo-data:
  neo-data:
