version: "3.8"

services:
  server-ci:
    build:
      context: ./server
      dockerfile: Dockerfile.production
    ports:
      - 3001:3001
    networks:
      - ci
    container_name: holenav-server-ci
    environment:
      - NODE_ENV=test
      - PORT=3001
      - DATABASE_URL=mongodb://db-ci/ci
      - CLIENT_URL=http://client-ci:3000
      - JWT_SECRET=asdasd
      - ENABLE_DEVTOOLS=true
    depends_on:
      - db-ci

  client-ci:
    build: ./client/
    ports:
      - 3000:3000
      - 30011:30011
    networks:
      - ci
    container_name: holenav-client-ci
    environment:
      - PORT=3000
      - INTERNAL_STATUS_PORT=30011
      - REACT_APP_CMS_URL=http://server-ci:3001
      - REACT_APP_ENABLE_DEVTOOLS=true

  db-ci:
    image: mongo:4.4-bionic
    restart: unless-stopped
    container_name: holenav-db-ci
    ports:
      - 27017:27017
    networks:
      - ci

  e2e-ci:
    build: ./e2e/
    networks:
      - ci
    container_name: holenav-e2e-ci
    environment:
      - CYPRESS_BASE_URL=http://client-ci:3000
      - CYPRESS_API_URL=http://server-ci:3001
    depends_on:
      - server-ci

networks:
  ci:
  