version: "3.8"

services:
  server:
    build: ./server/
    ports:
      - 3001:3001
    container_name: holenav-server
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=mongodb://db/holenav
    volumes:
      - ./server/src:/usr/src/app/src
    depends_on:
      - db

  client:
    build: ./client/
    ports:
      - 3000:3000
      - 30011:30011
    container_name: holenav-client
    environment:
      - PORT=3000
      - INTERNAL_STATUS_PORT=30011
    volumes:
      - ./client/src:/usr/src/app/src

  db:
    image: mongo:4.4-bionic
    restart: unless-stopped
    container_name: holenav-db
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27017:27017
