version: "3.8"

services:
  server:
    build: ./server/
    ports:
      - 3001:3001
    container_name: holenav-server
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URL=mongodb://mongo/holenav
      - NEO_URL=neo4j://neo
      - NEO_DB=neo4j
      - CLIENT_URL=http://localhost:3000
      - JWT_SECRET=asdasd
      - ENABLE_DEVTOOLS=true
    env_file:
      - .env.development
    volumes:
      - ./server/src:/usr/src/app/src
    depends_on:
      - mongo
      - neo

  client:
    build: ./client/
    ports:
      - 3000:3000
      - 30011:30011
    container_name: holenav-client
    environment:
      - PORT=3000
      - INTERNAL_STATUS_PORT=30011
      - REACT_APP_CMS_URL=http://localhost:3001
      - REACT_APP_ENABLE_DEVTOOLS=true
    volumes:
      - ./client/src:/usr/src/app/src

  mongo:
    image: mongo:5.0-focal
    restart: unless-stopped
    container_name: holenav-mongo
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
        volume:
          nocopy: true
    ports:
      - 27017:27017

  neo:
    image: neo4j:4.4
    restart: unless-stopped
    container_name: holenav-neo
    environment:
      - NEO4J_AUTH=none
    volumes:
      - type: volume
        source: neo-data
        target: /data
    ports:
      - 7474:7474
      - 7687:7687

  # Duplicate containers to enable an independent and hot-reloaded test env without ruining dev data.
  server-test:
    build: ./server/
    ports:
      - 4001:3001
    container_name: holenav-server-test
    environment:
      - NODE_ENV=test
      - PORT=3001
      - MONGO_URL=mongodb://mongo/holenav-test
      - NEO_URL=neo4j://neo
      - NEO_DB=neo4j
      - CLIENT_URL=http://localhost:4000
      - JWT_SECRET=asdasd
      - ENABLE_DEVTOOLS=true
    #env_file:
    #  - .env.development
    volumes:
      - ./server/src:/usr/src/app/src
    depends_on:
      - mongo
      - neo

  client-test:
    build: ./client/
    ports:
      - 4000:3000
      - 40011:30011
    container_name: holenav-client-test
    environment:
      - PORT=3000
      - INTERNAL_STATUS_PORT=30011
      - REACT_APP_CMS_URL=http://localhost:4001
      - REACT_APP_ENABLE_DEVTOOLS=true
    volumes:
      - ./client/src:/usr/src/app/src

volumes:
  mongo-data:
  neo-data:
