root: true
parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  # Keep prettier last so it overrides other configs correctly!
  - prettier
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "type|returns|of|unused"
