FROM node:16-alpine

# Install dependencies.
WORKDIR /usr/src/app
COPY ./package.json ./package-lock.json ./
RUN npm ci

COPY . .

# Build and clean up.
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ARG APP_VERSION
ENV APP_VERSION=${APP_VERSION}
RUN npm run build
RUN npm prune --production

CMD node dist/main.js
