FROM node:16-alpine

# Install dependencies.
WORKDIR /usr/src/app
COPY ./server/package.json ./server/package-lock.json ./
RUN npm ci

COPY ./server .
COPY ./data/staticData ./assets/staticData

# Build and clean up.
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
RUN npm run build
RUN npm prune --production

# Start via Nest in development mode.
CMD node dist/src/main.js
