apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: db-url
    namespace: holenav-staging
    envs:
    - .env

resources:
  - ingress.yaml
  - server.config.yaml
  - server.deployment.yaml
  - server.service.yaml
