name: Deploy client to CDN

on: workflow_dispatch

jobs:
  deploy-client:
    name: Deploy client to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy client to Vercel
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domains: |
            ${{ secrets.STAGING_DOMAIN }}
          working-directory: ./client
