name: Publish to staging

on:
  push:
    branches: [trunk]

jobs:
  deploy:
    name: Publish to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build server image and push it to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./server
          platforms: linux/amd64
          push: true
          tags: ${{ github.actor }}/holenav-server:staging
