name: Publish for staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Publish for staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build server image and push it to GHCR
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile.production
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.actor }}/holenav-server:staging
      - name: Deploy frontend to Vercel
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} 
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domains: |
            ${{ secrets.STAGING_DOMAIN }}
          working-directory: ./client
