name: Release new version

on:
  release:
    types: [released]

jobs:
  publish-server:
    name: Publish backend image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Parse semver number
        id: semver
        run: |
          PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
          echo "::set-output name=major::$(echo $PACKAGE_VERSION | cut -d "." -f 1)"
          echo "::set-output name=minor::$(echo $PACKAGE_VERSION | cut -d "." -f 2)"
          echo "::set-output name=patch::$(echo $PACKAGE_VERSION | cut -d "." -f 3)"
      - name: Compose semver tags
        id: tags
        run: |
          echo "::set-output name=major::v${{ steps.semver.outputs.major }}"
          echo "::set-output name=minor::v${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}"
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build server image and push it to GHCR
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile.production
          platforms: linux/amd64
          push: true
          build-args: |
            APP_VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/${{ github.actor }}/holenav-server:${{ github.ref_name }}
            ghcr.io/${{ github.actor }}/holenav-server:${{ steps.tags.outputs.major }}
            ghcr.io/${{ github.actor }}/holenav-server:${{ steps.tags.outputs.minor }}
            ghcr.io/${{ github.actor }}/holenav-server:latest

  publish-docs:
    name: Publish documentation
    needs: publish-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy documentation to Vercel
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domains: |
            ${{ secrets.DOCUMENTATION_DOMAIN }}
          working-directory: ./docs
