name: Run test suite

on:
  push:
    branches-ignore:
      - main

jobs:
  lint-client:
    name: Lint (client)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.4
      - name: Install dependencies
        working-directory: client
        run: npm ci
      - name: Lint client
        working-directory: client
        run: npm run lint

  lint-server:
    name: Lint (server)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.4
      - name: Install dependencies
        working-directory: server
        run: npm ci
      - name: Lint server
        working-directory: server
        run: npm run lint

  lint-e2e:
    name: Lint (E2E tests)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.4
      - name: Install dependencies
        working-directory: e2e
        run: npm ci
      - name: Lint E2E tests
        working-directory: e2e
        run: npm run lint

  test-server:
    name: Unit tests (server)
    runs-on: ubuntu-latest
    needs: lint-server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.4
      - name: Install dependencies
        working-directory: server
        run: npm ci
      - name: Run unit tests
        working-directory: server
        run: npm test

  test-e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    needs: [lint-client, lint-e2e, test-server]
    steps:
      - uses: actions/checkout@v2
      - name: Build and start containers
        run: docker-compose -f docker-compose-ci.yml up -d db-ci server-ci client-ci
      - name: Run E2E tests
        run: docker-compose -f docker-compose-ci.yml run e2e-ci

  test:
    name: Tests (OLD JOB)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.4
      - name: Run All Tests
        run: npm run test:ci
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress Results
          path: |
            e2e/cypress/videos
            e2e/cypress/screenshots
