name: Run test suite

on:
  push:
    branches-ignore:
      - update-docs

jobs:
  lint-client:
    name: Lint (client)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.4
      - name: Install dependencies
        run: npm ci
      - name: Lint client
        run: npm run lint

  lint-server:
    name: Lint (server)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.4
      - name: Install dependencies
        run: npm ci
      - name: Lint server
        run: npm run lint

  lint-e2e:
    name: Lint (E2E tests)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.4
      - name: Install dependencies
        run: npm ci
      - name: Lint E2E tests
        run: npm run lint

  test-server:
    name: Unit tests (server)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.4
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test

  test-e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and start containers
        run: docker-compose -f docker-compose-ci.yaml up -d mongo-ci neo-ci server-ci client-ci
      - name: Run E2E tests
        run: docker-compose -f docker-compose-ci.yaml run e2e-ci
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress Results
          path: |
            e2e/cypress/videos
            e2e/cypress/screenshots
