name: Run Test Suite

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.4
      - name: Run All Tests
        run: npm run test:ci
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress Results
          path: |
            e2e/cypress/videos
            e2e/cypress/screenshots
